### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by vyp** [Vannil/cheerilee.el#4]
I see that the cheerilee.info and cheerilee.texi files are under the GFDL, but the elisp files state that this file is not part of GNU Emacs, but then go on to say that GNU Emacs is under the GPL, without saying what cheerilee is under. Of course it's possible it was intended to have no license for cheerilee, but I'm hoping it was a mistake and you meant to say cheerilee instead of GNU Emacs in the elisp license headers?

**Comment by Vannil** [comment]
Yes, it's an error.
I forgot to change GNU Emacs to Cheerilee in the license.
I just pushed a fix, now the library should be properly licensed.

**Comment by vyp** [comment]
Sweet, thank you.
